apiVersion: apps/v1
kind: Deployment
metadata:
  ## Name and labels of the Deployment
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      ## The container to launch
      - image: backend
        name: backend
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 12345
    protocol: TCP
  selector:
    app: backend